//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCFPrøveeksamenTest.AuctionHouse {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AuktionsVare", Namespace="http://schemas.datacontract.org/2004/07/WcfWebApplication")]
    [System.SerializableAttribute()]
    public partial class AuktionsVare : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int BidCostumPhoneField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BidCustomNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int BidPriceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime BidTimeStampField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ItemDescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ItemNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int RatingPriceField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int BidCostumPhone {
            get {
                return this.BidCostumPhoneField;
            }
            set {
                if ((this.BidCostumPhoneField.Equals(value) != true)) {
                    this.BidCostumPhoneField = value;
                    this.RaisePropertyChanged("BidCostumPhone");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BidCustomName {
            get {
                return this.BidCustomNameField;
            }
            set {
                if ((object.ReferenceEquals(this.BidCustomNameField, value) != true)) {
                    this.BidCustomNameField = value;
                    this.RaisePropertyChanged("BidCustomName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int BidPrice {
            get {
                return this.BidPriceField;
            }
            set {
                if ((this.BidPriceField.Equals(value) != true)) {
                    this.BidPriceField = value;
                    this.RaisePropertyChanged("BidPrice");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime BidTimeStamp {
            get {
                return this.BidTimeStampField;
            }
            set {
                if ((this.BidTimeStampField.Equals(value) != true)) {
                    this.BidTimeStampField = value;
                    this.RaisePropertyChanged("BidTimeStamp");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ItemDescription {
            get {
                return this.ItemDescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.ItemDescriptionField, value) != true)) {
                    this.ItemDescriptionField = value;
                    this.RaisePropertyChanged("ItemDescription");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ItemNumber {
            get {
                return this.ItemNumberField;
            }
            set {
                if ((this.ItemNumberField.Equals(value) != true)) {
                    this.ItemNumberField = value;
                    this.RaisePropertyChanged("ItemNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int RatingPrice {
            get {
                return this.RatingPriceField;
            }
            set {
                if ((this.RatingPriceField.Equals(value) != true)) {
                    this.RatingPriceField = value;
                    this.RaisePropertyChanged("RatingPrice");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BidObject", Namespace="http://schemas.datacontract.org/2004/07/WcfWebApplication")]
    [System.SerializableAttribute()]
    public partial class BidObject : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CustomNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CustomPhoneField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ItemNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int PriceField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CustomName {
            get {
                return this.CustomNameField;
            }
            set {
                if ((object.ReferenceEquals(this.CustomNameField, value) != true)) {
                    this.CustomNameField = value;
                    this.RaisePropertyChanged("CustomName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CustomPhone {
            get {
                return this.CustomPhoneField;
            }
            set {
                if ((this.CustomPhoneField.Equals(value) != true)) {
                    this.CustomPhoneField = value;
                    this.RaisePropertyChanged("CustomPhone");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ItemNumber {
            get {
                return this.ItemNumberField;
            }
            set {
                if ((this.ItemNumberField.Equals(value) != true)) {
                    this.ItemNumberField = value;
                    this.RaisePropertyChanged("ItemNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Price {
            get {
                return this.PriceField;
            }
            set {
                if ((this.PriceField.Equals(value) != true)) {
                    this.PriceField = value;
                    this.RaisePropertyChanged("Price");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="AuctionHouse.IAuctionHouseService")]
    public interface IAuctionHouseService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAuctionHouseService/GetWares", ReplyAction="http://tempuri.org/IAuctionHouseService/GetWaresResponse")]
        WCFPrøveeksamenTest.AuctionHouse.AuktionsVare[] GetWares();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAuctionHouseService/GetWares", ReplyAction="http://tempuri.org/IAuctionHouseService/GetWaresResponse")]
        System.Threading.Tasks.Task<WCFPrøveeksamenTest.AuctionHouse.AuktionsVare[]> GetWaresAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAuctionHouseService/GetWare", ReplyAction="http://tempuri.org/IAuctionHouseService/GetWareResponse")]
        WCFPrøveeksamenTest.AuctionHouse.AuktionsVare GetWare(int IDNr);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAuctionHouseService/GetWare", ReplyAction="http://tempuri.org/IAuctionHouseService/GetWareResponse")]
        System.Threading.Tasks.Task<WCFPrøveeksamenTest.AuctionHouse.AuktionsVare> GetWareAsync(int IDNr);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAuctionHouseService/GiveBid", ReplyAction="http://tempuri.org/IAuctionHouseService/GiveBidResponse")]
        string GiveBid(WCFPrøveeksamenTest.AuctionHouse.BidObject bid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAuctionHouseService/GiveBid", ReplyAction="http://tempuri.org/IAuctionHouseService/GiveBidResponse")]
        System.Threading.Tasks.Task<string> GiveBidAsync(WCFPrøveeksamenTest.AuctionHouse.BidObject bid);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IAuctionHouseServiceChannel : WCFPrøveeksamenTest.AuctionHouse.IAuctionHouseService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AuctionHouseServiceClient : System.ServiceModel.ClientBase<WCFPrøveeksamenTest.AuctionHouse.IAuctionHouseService>, WCFPrøveeksamenTest.AuctionHouse.IAuctionHouseService {
        
        public AuctionHouseServiceClient() {
        }
        
        public AuctionHouseServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public AuctionHouseServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AuctionHouseServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AuctionHouseServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public WCFPrøveeksamenTest.AuctionHouse.AuktionsVare[] GetWares() {
            return base.Channel.GetWares();
        }
        
        public System.Threading.Tasks.Task<WCFPrøveeksamenTest.AuctionHouse.AuktionsVare[]> GetWaresAsync() {
            return base.Channel.GetWaresAsync();
        }
        
        public WCFPrøveeksamenTest.AuctionHouse.AuktionsVare GetWare(int IDNr) {
            return base.Channel.GetWare(IDNr);
        }
        
        public System.Threading.Tasks.Task<WCFPrøveeksamenTest.AuctionHouse.AuktionsVare> GetWareAsync(int IDNr) {
            return base.Channel.GetWareAsync(IDNr);
        }
        
        public string GiveBid(WCFPrøveeksamenTest.AuctionHouse.BidObject bid) {
            return base.Channel.GiveBid(bid);
        }
        
        public System.Threading.Tasks.Task<string> GiveBidAsync(WCFPrøveeksamenTest.AuctionHouse.BidObject bid) {
            return base.Channel.GiveBidAsync(bid);
        }
    }
}
